// <auto-generated />
namespace BooksAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NoFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211310599_NoFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
